"""
Django settings for PTG project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
# TODO Remove references to secrets.py before production
from . import secrets

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


#TODO Change before implementation
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@5s(-7@jbdu9kc)punrhi4y03ky3-@gr&yf-0xp_t3x=vc5pbm'

#TODO Set to false before implementation
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'pharmacy.apps.PharmacyConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PTG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PTG.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
###########################################################################################################
#                               TODO Change before production                                             #
#    Database details are to be kept in a file named secrets.py which git will ignore, keeping account    #
#    details offline. Name variables as seen below and assign values as string data types to work with    #
#    the settings below. For production this information will be set via environmental variables.         #
#                                                                                                         #
#    You will need to download psycopg2 connector to connect to database. Do this with                    #
#                                  ' pip install psycopg2 '                                               #
###########################################################################################################

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Database on server
        'NAME': secrets.dbname,
        # Username to log into server                      
        'USER': secrets.dbuser,
        # Database account password
        'PASSWORD': secrets.dbpass,
        # URL of server
        'HOST': secrets.dbhost,
        # Database server port
        'PORT': secrets.dbport,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
