# Generated by Django 2.1.7 on 2019-02-23 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_lot', models.IntegerField()),
                ('dose', models.CharField(blank=True, max_length=20)),
                ('count', models.IntegerField()),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('licence', models.IntegerField()),
                ('pack_size', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Generic',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('schedule', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_hospital', models.BooleanField(default=False)),
                ('is_clinic', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=14)),
                ('upstream_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='generic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Generic'),
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Manufacturer'),
        ),
        migrations.AddField(
            model_name='drug',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Location'),
        ),
        migrations.AddField(
            model_name='drug',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Brand'),
        ),
    ]
