# Generated by Django 2.1.7 on 2019-04-02 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Brand',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('license', models.IntegerField()),
                ('dose', models.TextField(blank=True, null=True)),
                ('pack_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Generic',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('schedule', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('upstream_supplier', models.IntegerField(blank=True, null=True)),
                ('is_hospital', models.BooleanField(default=False)),
                ('is_clinic', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_Origin', to='pharmacy.Location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_Destination', to='pharmacy.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='generic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Generic'),
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Manufacturer_Company'),
        ),
    ]
