# Generated by Django 2.1.7 on 2019-04-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('drug_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Location',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='order_detail',
            unique_together={('order_id', 'barcode')},
        ),
        migrations.AlterUniqueTogether(
            name='batch_location',
            unique_together={('batch_id', 'location_id')},
        ),
    ]
