# Generated by Django 2.1.7 on 2019-04-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20190402_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch_Location',
        ),
        migrations.DeleteModel(
            name='Order_Detail',
        ),
    ]
