# Generated by Django 2.1.7 on 2019-03-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_auto_20190224_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('batch_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch_Location',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufacturer_Company',
        ),
        migrations.DeleteModel(
            name='Disburse',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='location',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.DeleteModel(
            name='Receive',
        ),
        migrations.RenameField(
            model_name='drug_brand',
            old_name='licence',
            new_name='license',
        ),
        migrations.RemoveField(
            model_name='drug_brand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='drug_brand',
            name='pack_size',
        ),
        migrations.AlterField(
            model_name='location',
            name='upstream_supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.AlterUniqueTogether(
            name='order_detail',
            unique_together={('order_id', 'barcode')},
        ),
        migrations.AddField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pharmacy.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaction', to='pharmacy.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='batch_location',
            unique_together={('batch_id', 'location_id')},
        ),
        migrations.AddField(
            model_name='batch',
            name='drug_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Brand'),
        ),
    ]
