# Generated by Django 2.1.7 on 2019-03-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20190326_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_location',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='dose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drug_brand',
            name='pack_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_Origin', to='pharmacy.Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_Destination', to='pharmacy.Location'),
        ),
    ]
