# Generated by Django 2.1.7 on 2019-04-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20190403_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Batch')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Drug_Brand')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.Order')),
            ],
        ),
    ]
